---
    version: "3.9"
    services:
      api:
        build:
          context: .
        links:
          - "db"
        depends_on:
          - db
        ports:
          - "5000:5000"
        environment: 
          - DB_USER=postgres
          - DB_PASS=TopSecret123
          - DB_PORT=5432
          - DB_NAME=pgfib
      db:
        image: postgres:13
        environment:
          - POSTGRES_DB=pgfib
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=TopSecret123
        ports:
          - "5432:5432"
